### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by KeparYTbcc** [mishakorzik/IpHack#2]
![Screenshot_20211117_082734_com termux](https://user-images.githubusercontent.com/67996155/142209610-072b5175-3119-4281-9bd6-3f3e866a0644.png)

**Comment by mishakorzik** [comment]
Try reinstalling python. If it doesn't work then your python doesn't support encoding.

**Comment by mishakorzik** [comment]
what is your operating system?

**Comment by KeparYTbcc** [comment]
> what is your operating system?

huawei p20 pro (termux - no root)

**Comment by AAmoflex** [comment]
> Try reinstalling python. If it doesn't work then your python doesn't support encoding.

me to I have the same proplem
