### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AAmoflex** [mishakorzik/IpHack#3]
![Issue ip hack 2021-11-19 13:07:27](https://user-images.githubusercontent.com/94708402/142671019-cb7c4254-dd07-4a1c-a07c-6b1d0ddf2aab.png)

**Comment by mishakorzik** [comment]
What you operating system.

**Comment by AAmoflex** [comment]
it's kali linux

**Comment by mishakorzik** [comment]
Kali Linux not supported.
