### ISSUE TITLE
Non-UTF-8 code starting with '\x8d¡

### ISSUE THREAD

**Issue by MrRobotEs** [mishakorzik/IpHack#8]
when I try to "hack" an ip I get this error, I don't know how to solve it, the complete error is:

`SyntaxError: Non-UTF-8 code starting with '\x8d' in file /home/kali/IpHack/IpHack.py on line 5, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details`

I get the error in kali linux and in termux

**Comment by mishakorzik** [comment]
Not supported Kali linux
